#!/bin/bash

# Quick commands for Cheeta Webapp development

echo "🐆 Cheeta Webapp - Quick Commands"
echo ""
echo "📱 RUN & BUILD:"
echo "  ./gradlew bootRun          # Run development server (http://localhost:8080)"
echo "  ./gradlew build -x test    # Build production JAR"
echo "  ./gradlew clean            # Clean build artifacts"
echo ""
echo "🧪 TESTING:"
echo "  ./gradlew test             # Run all tests"
echo "  ./gradlew test --tests SomeTest    # Run specific test"
echo ""
echo "📚 INFORMATION:"
echo "  ./gradlew tasks            # List all available Gradle tasks"
echo "  ./gradlew dependencies     # Show dependency tree"
echo ""
echo "🔧 DEVELOPMENT:"
echo "  ./gradlew bootRun --info   # Run with info logging"
echo "  ./gradlew bootRun --debug  # Run with debug logging"
echo ""
echo "🌐 USEFUL URLS:"
echo "  http://localhost:8080                    # Webapp"
echo "  http://localhost:8081/rest              # Server-core API (when running)"
echo "  http://localhost:8080/h2-console        # H2 database console (dev only)"
echo ""
echo "📖 DOCUMENTATION:"
echo "  cat QUICK_START.md         # Quick reference"
echo "  cat DEVELOPMENT.md         # Detailed development guide"
echo "  cat IMPLEMENTATION.md      # Implementation details"
echo ""
