#!/usr/bin/env python3
import os
from pathlib import Path

def create_file(path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).touch()

def create_dir(path):
    Path(path).mkdir(parents=True, exist_ok=True)

base = "cheeta-webapp"

dirs = [
    f"{base}/src/main/kotlin/io/cheeta",
    f"{base}/src/main/kotlin/io/cheeta/config",
    f"{base}/src/main/kotlin/io/cheeta/security",
    f"{base}/src/main/kotlin/io/cheeta/api",
    f"{base}/src/main/kotlin/io/cheeta/api/client",
    f"{base}/src/main/kotlin/io/cheeta/api/dto",
    f"{base}/src/main/kotlin/io/cheeta/views",
    f"{base}/src/main/kotlin/io/cheeta/views/dashboard",
    f"{base}/src/main/kotlin/io/cheeta/views/ai",
    f"{base}/src/main/kotlin/io/cheeta/views/feed",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components",
    f"{base}/src/main/kotlin/io/cheeta/views/repository",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/commits",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/branches",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/tags",
    f"{base}/src/main/kotlin/io/cheeta/views/issues",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/list",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/detail",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/kanban",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/list",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/detail",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/review",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/pipelines",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/builds",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/logs",
    f"{base}/src/main/kotlin/io/cheeta/views/profile",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/activity",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/contributions",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/settings",
    f"{base}/src/main/kotlin/io/cheeta/views/social",
    f"{base}/src/main/kotlin/io/cheeta/views/social/feeds",
    f"{base}/src/main/kotlin/io/cheeta/views/social/users",
    f"{base}/src/main/kotlin/io/cheeta/views/social/organizations",
    f"{base}/src/main/kotlin/io/cheeta/views/settings",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/general",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/security",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/integrations",
    f"{base}/src/main/kotlin/io/cheeta/views/admin",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/users",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/organizations",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/system",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/board",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/applications",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/myprofile",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/dashboard",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/discover",
    f"{base}/src/main/kotlin/io/cheeta/views/packages",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/registry",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/publish",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/browser",
    f"{base}/src/main/kotlin/io/cheeta/views/pages",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/builder",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/deploy",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/dora",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/team",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/custom",
    f"{base}/src/main/kotlin/io/cheeta/views/templates",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/marketplace",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/create",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/editor",
    f"{base}/src/main/kotlin/io/cheeta/components",
    f"{base}/src/main/kotlin/io/cheeta/components/layout",
    f"{base}/src/main/kotlin/io/cheeta/components/cards",
    f"{base}/src/main/kotlin/io/cheeta/components/lists",
    f"{base}/src/main/kotlin/io/cheeta/components/forms",
    f"{base}/src/main/kotlin/io/cheeta/components/navigation",
    f"{base}/src/main/kotlin/io/cheeta/components/code",
    f"{base}/src/main/kotlin/io/cheeta/components/charts",
    f"{base}/src/main/kotlin/io/cheeta/components/dialogs",
    f"{base}/src/main/kotlin/io/cheeta/components/notifications",
    f"{base}/src/main/kotlin/io/cheeta/services",
    f"{base}/src/main/kotlin/io/cheeta/services/ai",
    f"{base}/src/main/kotlin/io/cheeta/services/feed",
    f"{base}/src/main/kotlin/io/cheeta/services/notifications",
    f"{base}/src/main/kotlin/io/cheeta/services/search",
    f"{base}/src/main/kotlin/io/cheeta/services/analytics",
    f"{base}/src/main/kotlin/io/cheeta/utils",
    f"{base}/src/main/kotlin/io/cheeta/utils/extensions",
    f"{base}/src/main/kotlin/io/cheeta/utils/formatters",
    f"{base}/src/main/kotlin/io/cheeta/utils/validators",
    f"{base}/src/main/kotlin/io/cheeta/models",
    f"{base}/src/main/kotlin/io/cheeta/models/ai",
    f"{base}/src/main/kotlin/io/cheeta/models/feed",
    f"{base}/src/main/kotlin/io/cheeta/models/social",
    f"{base}/src/main/kotlin/io/cheeta/models/repository",
    f"{base}/src/main/kotlin/io/cheeta/models/cicd",
    f"{base}/src/main/resources",
    f"{base}/src/main/resources/META-INF/resources",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/components",
    f"{base}/src/main/resources/META-INF/resources/icons",
    f"{base}/src/main/resources/META-INF/resources/images",
    f"{base}/src/main/resources/META-INF/resources/fonts",
    f"{base}/src/test/kotlin/io/cheeta",
    f"{base}/src/test/kotlin/io/cheeta/views",
    f"{base}/src/test/kotlin/io/cheeta/components",
    f"{base}/src/test/kotlin/io/cheeta/services",
    f"{base}/src/test/kotlin/io/cheeta/api",
    f"{base}/src/test/kotlin/io/cheeta/integration",
    f"{base}/frontend",
    f"{base}/frontend/themes",
    f"{base}/frontend/themes/cheeta",
    f"{base}/frontend/styles",
    f"{base}/frontend/generated",
    f"{base}/.github",
    f"{base}/.github/workflows",
    f"{base}/docs",
    f"{base}/docs/architecture",
    f"{base}/docs/components",
    f"{base}/docs/api",
    f"{base}/scripts",
    f"{base}/config",
    f"{base}/config/dev",
    f"{base}/config/prod",
]

for d in dirs:
    create_dir(d)

files = [
    f"{base}/build.gradle.kts",
    f"{base}/settings.gradle.kts",
    f"{base}/gradle.properties",
    f"{base}/gradlew",
    f"{base}/gradlew.bat",
    f"{base}/.gitignore",
    f"{base}/README.md",
    f"{base}/LICENSE",
    f"{base}/CHANGELOG.md",
    f"{base}/CONTRIBUTING.md",
    f"{base}/Dockerfile",
    f"{base}/docker-compose.yml",
    f"{base}/.dockerignore",
    f"{base}/.editorconfig",
    
    f"{base}/src/main/kotlin/io/cheeta/Application.kt",
    f"{base}/src/main/kotlin/io/cheeta/MainLayout.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/config/VaadinConfig.kt",
    f"{base}/src/main/kotlin/io/cheeta/config/SecurityConfig.kt",
    f"{base}/src/main/kotlin/io/cheeta/config/ApiConfig.kt",
    f"{base}/src/main/kotlin/io/cheeta/config/CorsConfig.kt",
    f"{base}/src/main/kotlin/io/cheeta/config/WebSocketConfig.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/security/SecurityService.kt",
    f"{base}/src/main/kotlin/io/cheeta/security/AuthenticationProvider.kt",
    f"{base}/src/main/kotlin/io/cheeta/security/SessionManager.kt",
    f"{base}/src/main/kotlin/io/cheeta/security/PermissionChecker.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/api/client/OneDevClient.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/client/ApiClient.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/client/WebSocketClient.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/api/dto/UserDto.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/dto/RepositoryDto.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/dto/IssueDto.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/dto/PullRequestDto.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/dto/BuildDto.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/dto/CommitDto.kt",
    f"{base}/src/main/kotlin/io/cheeta/api/dto/BranchDto.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/dashboard/DashboardView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/dashboard/ActivityFeed.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/dashboard/QuickActions.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/dashboard/RecentRepos.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/dashboard/TrendingRepos.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/ai/AIChatView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/ai/AIAssistantPanel.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/ai/CodeReviewAssistant.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/ai/ChatMessage.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/ai/ConversationHistory.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/ai/AISettings.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/feed/DevFeedView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/QuestionView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/DiscussionView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/SolutionView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/PostComposer.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/PostList.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/PostDetail.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/TagsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/TrendingView.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components/PostCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components/CommentSection.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components/VotingWidget.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components/TagChip.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components/UserBadge.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/feed/components/CodeBlock.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/repository/RepositoryView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/RepositoryHeader.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/RepositoryTabs.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser/FileBrowserView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser/FileViewer.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser/FileTree.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser/CodeViewer.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser/DiffViewer.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/browser/BlameView.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/repository/commits/CommitListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/commits/CommitDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/commits/CommitCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/commits/CommitGraph.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/repository/branches/BranchListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/branches/BranchCompareView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/branches/BranchCard.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/repository/tags/TagListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/tags/TagDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/repository/tags/ReleaseView.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/issues/IssuesView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/list/IssueListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/list/IssueFilters.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/list/IssueCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/detail/IssueDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/detail/IssueTimeline.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/detail/IssueComments.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/kanban/KanbanView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/kanban/KanbanColumn.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/issues/kanban/KanbanCard.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/PullRequestsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/list/PRListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/list/PRFilters.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/list/PRCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/detail/PRDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/detail/PRTimeline.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/detail/PRFiles.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/detail/PRChecks.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/review/ReviewView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/review/ReviewComments.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pullrequests/review/ReviewSummary.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/CICDView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/pipelines/PipelineListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/pipelines/PipelineDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/pipelines/PipelineEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/builds/BuildListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/builds/BuildDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/builds/BuildCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/logs/LogViewer.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/cicd/logs/LogStream.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/profile/ProfileView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/ProfileHeader.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/activity/ActivityView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/activity/ActivityTimeline.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/activity/ActivityCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/contributions/ContributionGraph.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/contributions/ContributionCalendar.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/settings/ProfileSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/settings/AccountSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/profile/settings/NotificationSettings.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/social/SocialView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/feeds/PersonalFeed.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/feeds/TeamFeed.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/feeds/OrganizationFeed.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/feeds/TrendingFeed.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/users/UserListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/users/UserCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/users/FollowersView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/users/FollowingView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/organizations/OrgListView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/organizations/OrgCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/social/organizations/OrgMembers.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/settings/SettingsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/general/GeneralSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/general/ThemeSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/general/LanguageSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/security/SecuritySettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/security/TwoFactorSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/security/TokensView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/integrations/IntegrationsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/integrations/WebhooksView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/settings/integrations/ApiKeysView.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/admin/AdminView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/users/UserManagementView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/users/UserList.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/users/UserEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/organizations/OrgManagementView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/organizations/OrgList.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/organizations/OrgEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/system/SystemSettings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/system/SystemHealth.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/system/SystemLogs.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/admin/system/SystemMetrics.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/JobBoardView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/board/JobListingCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/board/JobSearchFilters.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/board/JobDetailView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/board/CompanyProfileView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/applications/ApplicationsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/applications/ApplicationCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/applications/ApplicationDetail.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/applications/ApplicationTracker.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/myprofile/PortfolioView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/myprofile/SkillsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/myprofile/ReputationView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/jobs/myprofile/ContributionMetrics.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/SponsorsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/dashboard/SponsorDashboard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/dashboard/SponsorshipStats.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/dashboard/SponsorTiers.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/dashboard/FundingProgress.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/dashboard/SponsorsList.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/discover/DiscoverProjectsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/discover/ProjectCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/discover/SponsorMatcher.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/sponsors/discover/SponsorshipFlow.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/packages/PackagesView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/registry/RegistryView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/registry/PackageCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/registry/RegistrySearch.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/registry/VersionHistory.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/publish/PublishView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/publish/PackageEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/publish/PublishFlow.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/browser/PackageBrowser.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/browser/PackageDetail.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/packages/browser/DependencyGraph.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/pages/PagesView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/builder/PageBuilder.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/builder/BlockEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/builder/TemplateSelector.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/builder/StyleEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/deploy/DeploymentView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/deploy/DomainManager.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/deploy/DeploymentHistory.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/pages/deploy/SSLManager.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/AnalyticsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/dora/DORAMetricsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/dora/DeploymentFrequencyChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/dora/LeadTimeChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/dora/MTTRChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/dora/ChangeFailureRateChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/team/TeamAnalyticsView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/team/CollaborationMetrics.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/team/CodeQualityTrends.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/team/TeamVelocity.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/custom/CustomDashboard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/custom/DashboardBuilder.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/custom/WidgetLibrary.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/analytics/custom/DataExporter.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/views/templates/TemplatesView.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/marketplace/TemplateMarketplace.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/marketplace/TemplateCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/marketplace/TemplateSearch.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/marketplace/TemplateRatings.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/create/TemplateCreator.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/create/TemplateEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/create/TemplatePreview.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/editor/VisualTemplateBuilder.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/editor/TemplateYAMLEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/editor/TemplateValidator.kt",
    f"{base}/src/main/kotlin/io/cheeta/views/templates/editor/TemplateVersionControl.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/layout/AppLayout.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/layout/NavigationBar.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/layout/SideBar.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/layout/Footer.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/layout/PageHeader.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/cards/Card.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/cards/RepoCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/cards/UserCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/cards/StatCard.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/cards/ActivityCard.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/lists/ItemList.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/lists/VirtualList.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/lists/InfiniteScroll.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/lists/FilterableList.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/forms/FormField.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/forms/FormValidator.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/forms/MarkdownEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/forms/CodeEditor.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/forms/SearchField.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/navigation/Breadcrumb.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/navigation/Tabs.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/navigation/Pagination.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/navigation/Menu.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/code/SyntaxHighlighter.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/code/CodeBlock.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/code/DiffView.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/code/LineNumbers.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/charts/LineChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/charts/BarChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/charts/PieChart.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/charts/ContributionChart.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/dialogs/ConfirmDialog.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/dialogs/FormDialog.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/dialogs/InfoDialog.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/components/notifications/Toast.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/notifications/NotificationBadge.kt",
    f"{base}/src/main/kotlin/io/cheeta/components/notifications/NotificationPanel.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/ai/AIService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/ai/ChatService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/ai/CodeReviewService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/ai/CompletionService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/ai/EmbeddingService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/feed/FeedService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/feed/PostService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/feed/CommentService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/feed/VoteService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/feed/TagService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/notifications/NotificationService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/notifications/EmailService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/notifications/WebSocketService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/notifications/PushService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/search/SearchService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/search/CodeSearchService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/search/SemanticSearchService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/search/IndexService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/analytics/AnalyticsService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/analytics/MetricsService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/analytics/DORAMetricsService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/analytics/UsageTracker.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/jobs/JobBoardService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/jobs/JobApplicationService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/jobs/CandidateMatchingService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/jobs/PortfolioService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/jobs/ReputationService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/sponsors/SponsorshipService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/sponsors/PaymentService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/sponsors/TierService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/sponsors/SponsorMatchingService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/packages/PackageService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/packages/RegistryService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/packages/PublishService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/packages/DependencyService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/packages/VulnerabilityScanService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/pages/PageService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/pages/PageBuilderService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/pages/DeploymentService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/pages/DomainService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/pages/CDNService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/services/templates/TemplateService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/templates/TemplateMarketplaceService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/templates/TemplateValidationService.kt",
    f"{base}/src/main/kotlin/io/cheeta/services/templates/TemplateInstallService.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/utils/extensions/StringExtensions.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/extensions/DateExtensions.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/extensions/CollectionExtensions.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/extensions/VaadinExtensions.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/utils/formatters/DateFormatter.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/formatters/NumberFormatter.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/formatters/MarkdownFormatter.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/formatters/CodeFormatter.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/utils/validators/EmailValidator.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/validators/UrlValidator.kt",
    f"{base}/src/main/kotlin/io/cheeta/utils/validators/FormValidator.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/ai/ChatMessage.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/ai/Conversation.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/ai/AIResponse.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/ai/CodeReview.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/ai/Suggestion.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Post.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Question.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Discussion.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Solution.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Comment.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Vote.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/feed/Tag.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/social/User.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/social/Profile.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/social/Activity.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/social/Follow.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/social/Star.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/social/Achievement.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/repository/Repository.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/repository/Commit.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/repository/Branch.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/repository/Tag.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/repository/File.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/cicd/Pipeline.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/cicd/Build.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/cicd/Job.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/cicd/Artifact.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/jobs/JobListing.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/jobs/JobApplication.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/jobs/CompanyProfile.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/jobs/Candidate.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/jobs/JobMatch.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/sponsors/Sponsorship.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/sponsors/Tier.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/sponsors/Payment.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/sponsors/SponsorBenefit.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/packages/Package.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/packages/PackageVersion.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/packages/Dependency.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/packages/Vulnerability.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/pages/Page.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/pages/PageBlock.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/pages/PageDeployment.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/pages/CustomDomain.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/analytics/Metric.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/analytics/DORAMetrics.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/analytics/TeamMetrics.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/analytics/Dashboard.kt",
    
    f"{base}/src/main/kotlin/io/cheeta/models/templates/Template.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/templates/TemplateVersion.kt",
    f"{base}/src/main/kotlin/io/cheeta/models/templates/TemplateVariable.kt",
    
    f"{base}/src/main/resources/application.yml",
    f"{base}/src/main/resources/application-dev.yml",
    f"{base}/src/main/resources/application-prod.yml",
    f"{base}/src/main/resources/logback.xml",
    f"{base}/src/main/resources/banner.txt",
    f"{base}/src/main/resources/messages.properties",
    f"{base}/src/main/resources/messages_en.properties",
    f"{base}/src/main/resources/messages_es.properties",
    f"{base}/src/main/resources/messages_fr.properties",
    
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/theme.json",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/colors.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/typography.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/spacing.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/layout.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/buttons.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/forms.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/cards.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/navigation.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/code.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/styles/dark-mode.css",
    
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/components/card.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/components/button.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/components/input.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/components/dialog.css",
    f"{base}/src/main/resources/META-INF/resources/themes/cheeta/components/notification.css",
    
    f"{base}/src/test/kotlin/io/cheeta/ApplicationTest.kt",
    
    f"{base}/src/test/kotlin/io/cheeta/views/DashboardViewTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/views/AIChatViewTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/views/DevFeedViewTest.kt",
    
    f"{base}/src/test/kotlin/io/cheeta/components/CardTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/components/ListTest.kt",
    
    f"{base}/src/test/kotlin/io/cheeta/services/AIServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/FeedServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/NotificationServiceTest.kt",
    
    f"{base}/src/test/kotlin/io/cheeta/api/OneDevClientTest.kt",
    
    f"{base}/src/test/kotlin/io/cheeta/integration/LoginFlowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/AIWorkflowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/FeedWorkflowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/JobBoardWorkflowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/SponsorsWorkflowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/PackagesWorkflowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/PagesWorkflowTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/integration/AnalyticsWorkflowTest.kt",
    
    f"{base}/src/test/kotlin/io/cheeta/services/JobBoardServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/SponsorshipServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/PackageServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/PageServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/TemplateServiceTest.kt",
    f"{base}/src/test/kotlin/io/cheeta/services/AnalyticsServiceTest.kt",
    
    f"{base}/frontend/themes/cheeta/theme.json",
    f"{base}/frontend/themes/cheeta/styles.css",
    f"{base}/frontend/styles/shared-styles.css",
    
    f"{base}/.github/workflows/build.yml",
    f"{base}/.github/workflows/test.yml",
    f"{base}/.github/workflows/deploy.yml",
    f"{base}/.github/workflows/release.yml",
    f"{base}/.github/PULL_REQUEST_TEMPLATE.md",
    f"{base}/.github/ISSUE_TEMPLATE/bug_report.md",
    f"{base}/.github/ISSUE_TEMPLATE/feature_request.md",
    
    f"{base}/docs/README.md",
    f"{base}/docs/SETUP.md",
    f"{base}/docs/DEVELOPMENT.md",
    f"{base}/docs/DEPLOYMENT.md",
    f"{base}/docs/ARCHITECTURE.md",
    f"{base}/docs/API.md",
    
    f"{base}/docs/architecture/overview.md",
    f"{base}/docs/architecture/services.md",
    f"{base}/docs/architecture/data-flow.md",
    f"{base}/docs/architecture/security.md",
    f"{base}/docs/architecture/scaling.md",
    
    f"{base}/docs/components/overview.md",
    f"{base}/docs/components/layout.md",
    f"{base}/docs/components/forms.md",
    f"{base}/docs/components/cards.md",
    f"{base}/docs/components/navigation.md",
    
    f"{base}/docs/api/onedev-integration.md",
    f"{base}/docs/api/websocket.md",
    f"{base}/docs/api/rest.md",
    
    f"{base}/scripts/build.sh",
    f"{base}/scripts/test.sh",
    f"{base}/scripts/deploy.sh",
    f"{base}/scripts/dev.sh",
    f"{base}/scripts/lint.sh",
    f"{base}/scripts/format.sh",
    f"{base}/scripts/clean.sh",
    
    f"{base}/config/dev/application.yml",
    f"{base}/config/dev/nginx.conf",
    
    f"{base}/config/prod/application.yml",
    f"{base}/config/prod/nginx.conf",
    f"{base}/config/prod/docker-compose.yml",
]

for f in files:
    create_file(f)

gradle_wrapper_dir = f"{base}/gradle/wrapper"
create_dir(gradle_wrapper_dir)
create_file(f"{gradle_wrapper_dir}/gradle-wrapper.properties")
create_file(f"{gradle_wrapper_dir}/gradle-wrapper.jar")

print(f"✅ Cheeta Vaadin webapp scaffolded at: {base}/")
print(f"📁 Created {len(dirs)} directories")
print(f"📄 Created {len(files)} files")
print(f"\nNext steps:")
print(f"  cd {base}")
print(f"  ./gradlew build")
print(f"  ./gradlew bootRun")
